name: My second Workflow
# trigger events,space to indicate array
on:
 push:
  branches:
  - 'release/*'
#-pull

#jobs in workflow,name
#cannot be tab must be space
jobs:
  mysecondWorkFlow:
  #OS that job will be running on
    runs-on: ubuntu-latest

  # array of steps to perform task
    steps:
    - name: echo the date
      run : echo "the current time and date is ${{ github.ref_name}}"
    - name: checkout current repo
      uses : actions/checkout@v3
    