name: release and deploy
# trigger events,space to indicate array
on:
 push:
 # 1 or more
  branches:
  - "release/.+"
  - "release/*"
#-pull

#jobs in workflow,name
#cannot be tab must be space
 jobs:
   release and deploy:
  #OS that job will be running on
    runs-on: ubuntu-latest
    # array of steps to perform task
    steps:
    - name: Echo the branch name
     run : echo "current branch -${{ github.ref_name}}"
    - name: Checkout the branch
     uses: actions/checkout@v3
     with:
      ref:${{github.ref_name}}
    